using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GrandiaRandomizer
{
    public class ItemLocationChecker
    {
        public static string ItemLocation(Int32 Id)
        {
            switch (Id)
            {
                case 1: return "Not Used";
                case 2: return "Not Used";
                case 3: return "Not Used";
                case 4: return "Not Used";
                case 5: return "Not Used";
                case 6: return "Not Used";
                case 7: return "Not Used";
                case 8: return "Not Used";
                case 9: return "Not Used";
                case 10: return "Item Key";
                case 11: return "Item Key";
                case 12: return "Item Key";
                case 13: return "Item Key";
                case 14: return "Item Key";
                case 15: return "Item Key";
                case 16: return "Item Key";
                case 17: return "Item Key";
                case 18: return "Item key";
                case 19: return "Item Key";
                case 20: return "Item Key";
                case 21: return "Item Key";
                case 22: return "Item Key";
                case 23: return "Item Key";
                case 24: return "Item Key";
                case 25: return "Item Key";
                case 26: return "Item Key";
                case 27: return "Item Key";
                case 28: return "Item Key";
                case 29: return "Item Key";
                case 30: return "Item Key";
                case 31: return "Item Key";
                case 32: return "Item Key";
                case 33: return "Item Key";
                case 34: return "Item Key";
                case 35: return "Item Key";
                case 36: return "Buy : Cafu Village, Find : Petrified Forest";
                case 37: return "Item Key";
                case 38: return "Find: Parm.";
                case 39: return "Item Key";
                case 40: return "";
                case 41: return "Item Key";
                case 42: return "";
                case 43: return "Find: Steamer.";
                case 44: return "";
                case 45: return "Not Available";
                case 46: return "?";
                case 47: return "Buy: Field Base.";
                case 48: return "Not Used";
                case 49: return "Not Used";
                case 50: return "Not Used";
                case 51: return "Not Used";
                case 52: return "Not Used";
                case 53: return "Not Used";
                case 54: return "Not Used";
                case 55: return "Not Used";
                case 56: return "Not Used";
                case 57: return "Not Used";
                case 58: return "Not Used";
                case 59: return "Not Used";
                case 60: return "Not Used";
                case 61: return "Not Used";
                case 62: return "Not Used";
                case 63: return "";
                case 64: return "";
                case 65: return "";
                case 66: return "";
                case 67: return "";
                case 68: return "";
                case 69: return "";
                case 70: return "";
                case 71: return "";
                case 72: return "";
                case 73: return "";
                case 74: return "";
                case 75: return "";
                case 76: return "";
                case 77: return "";
                case 78: return "";
                case 79: return "Original Location";
                case 80: return "";
                case 81: return "Not Used";
                case 82: return "";
                case 83: return "";
                case 84: return "";
                case 85: return "";
                case 86: return "";
                case 87: return "";
                case 88: return "";
                case 89: return "";
                case 90: return "";
                case 91: return "";
                case 92: return "";
                case 93: return "Not Used";
                case 94: return "";
                case 95: return "";
                case 96: return "";
                case 97: return "";
                case 98: return "";
                case 99: return "";
                case 100: return "Original Location";
                case 101: return "";
                case 102: return "";
                case 103: return "Original Location";
                case 104: return "";
                case 105: return "";
                case 106: return "";
                case 107: return "";
                case 108: return "";
                case 109: return "";
                case 110: return "";
                case 111: return "";
                case 112: return "";
                case 113: return "";
                case 114: return "";
                case 115: return "";
                case 116: return "";
                case 117: return "";
                case 118: return "";
                case 119: return "";
                case 120: return "";
                case 121: return "";
                case 122: return "";
                case 123: return "";
                case 124: return "";
                case 125: return "";
                case 126: return "";
                case 127: return "";
                case 128: return "";
                case 129: return "";
                case 130: return "";
                case 131: return "";
                case 132: return "";
                case 133: return "";
                case 134: return "";
                case 135: return "Original Location";
                case 136: return "";
                case 137: return "";
                case 138: return "";
                case 139: return "";
                case 140: return "";
                case 141: return "";
                case 142: return "";
                case 143: return "";
                case 144: return "";
                case 145: return "";
                case 146: return "";
                case 147: return "";
                case 148: return "";
                case 149: return "";
                case 150: return "";
                case 151: return "";
                case 152: return "Original Location";
                case 153: return "Original Location";
                case 154: return "";
                case 155: return "";
                case 156: return "";
                case 157: return "";
                case 158: return "";
                case 159: return "";
                case 160: return "";
                case 161: return "";
                case 162: return "";
                case 163: return "";
                case 164: return "";
                case 165: return "";
                case 166: return "";
                case 167: return "";
                case 168: return "";
                case 169: return "";
                case 170: return "";
                case 171: return "";
                case 172: return "";
                case 173: return "";
                case 174: return "";
                case 175: return "";
                case 176: return "";
                case 177: return "";
                case 178: return "";
                case 179: return "";
                case 180: return "";
                case 181: return "";
                case 182: return "";
                case 183: return "";
                case 184: return "";
                case 185: return "";
                case 186: return "";
                case 187: return "";
                case 188: return "";
                case 189: return "";
                case 190: return "";
                case 191: return "";
                case 192: return "";
                case 193: return "";
                case 194: return "";
                case 195: return "";
                case 196: return "";
                case 197: return "";
                case 198: return "";
                case 199: return "";
                case 200: return "";
                case 201: return "";
                case 202: return "";
                case 203: return "";
                case 204: return "";
                case 205: return "";
                case 206: return "";
                case 207: return "";
                case 208: return "";
                case 209: return "";
                case 210: return "";
                case 211: return "";
                case 212: return "";
                case 213: return "";
                case 214: return "";
                case 215: return "";
                case 216: return "";
                case 217: return "";
                case 218: return "";
                case 219: return "";
                case 220: return "";
                case 221: return "";
                case 222: return "";
                case 223: return "";
                case 224: return "";
                case 225: return "";
                case 226: return "";
                case 227: return "";
                case 228: return "";
                case 229: return "";
                case 230: return "";
                case 231: return "";
                case 232: return "";
                case 233: return "";
                case 234: return "";
                case 235: return "";
                case 236: return "";
                case 237: return "";
                case 238: return "";
                case 239: return "";
                case 240: return "";
                case 241: return "";
                case 242: return "";
                case 243: return "";
                case 244: return "";
                case 245: return "";
                case 246: return "";
                case 247: return "";
                case 248: return "";
                case 249: return "";
                case 250: return "";
                case 251: return "";
                case 252: return "";
                case 253: return "";
                case 254: return "";
                case 255: return "";
                case 256: return "";
                case 257: return "";
                case 258: return "";
                case 259: return "";
                case 260: return "";
                case 261: return "";
                case 262: return "";
                case 263: return "";
                case 264: return "";
                case 265: return "";
                case 266: return "";
                case 267: return "";
                case 268: return "";
                case 269: return "";
                case 270: return "";
                case 271: return "";
                case 272: return "";
                case 273: return "";
                case 274: return "";
                case 275: return "Not Used";
                case 276: return "Find: Soldier's Graveyard (B5).";
                case 277: return "Justin's Initial Equipment";
                case 278: return "Find: Mt. Typhoon (Peak)";
                case 279: return "Find: Military Train";
                case 280: return "Buy: Cafu. Rapp's Begins with this";
                case 281: return "Laine.";
                case 282: return "Milda's Initial Equipment. Buy: Zil Padon, Zil Padon Ruins.";
                case 283: return "Find: Soldier's Graveyard (B2).";
                case 284: return "Find: Valley of the Flying Dragon (3), Volcano Slope(2). Drop: Klepp Knight, Lost Soul. Buy Teleport Room (Tower of Temptation).";
                case 285: return "Find: Virgin Forest (2). Buy Teleport Room (Tower of Temptation).";
                case 286: return "Find: Ghost Ship (Lower Deck), Mysterious Vanishing Hill. Buy: Teleport Room (Tower of Temptation).";
                case 287: return "Find: Underground Ruins (B2). Buy: Teleport Room (Tower of Temptation).";
                case 288: return "Find: Underground Ruins (Shrine 1).";
                case 289: return "Buy: Teleportation Room (Tower Of Temptation)";
                case 290: return "Find: Tower of Temptation (2nd Floor). Buy: Teleportation Room (Tower of Temptation).";
                case 291: return "Sue's Initial Equipment (Only for Sue)";
                case 292: return "Feena's Initial Equipment.";
                case 293: return "Buy: Luc, Teleportation Room (Tower of Temptation)";
                case 294: return "Find: God of Light Mountain (Peak).";
                case 295: return "Gadwin's Initial Equipment";
                case 296: return "Buy: Gumbo.";
                case 297: return "";
                case 298: return "Buy: Laine";
                case 299: return "Find: West Rangle Mountains, Soldier's Graveyard (B4 East).";
                case 300: return "Find: Gaia (3)";
                case 301: return "";
                case 302: return "Find: Underground Ruins (2). Drop: Salamadile.";
                case 303: return "Find: Twin Towers (South).";
                case 304: return "Find: South Brinan Plateau.";
                case 305: return "";
                case 306: return "Find: Petrified Forest (2).";
                case 307: return "Find: Typhoon Tower (1), Vocalno. Buy: Cafu.";
                case 308: return "Find: God of Light Mountain (Foot), Petrified Forest.";
                case 309: return "Find: Icarian City, Buy: Laine, Drop: Medusa Dancer";
                case 310: return "Find: Twin Towers (North).";
                case 311: return "";
                case 312: return "Find: Gaia (1).Buy: Zil Padon, Zil Padon Ruins.";
                case 313: return "Find: Tower of Temptation (Top Floor).";
                case 314: return "Drop: Klepp Rider. Buy: Gumbo, Teleportation Room (Tower of Temptation)";
                case 315: return "Find: Twin Towers (North), Underground Ruins (4), Tower of Temptation's Roof (X2), Spirit Sanctuary (1). Drop: Great Susano-o.";
                case 316: return "Not Used";
                case 317: return "Guido's Initial Equipment. Buy: in Zil Padon, Zil Padon Ruins. Drop: Gill Newt.";
                case 318: return "Find: South Lama Mountains, Underground Ruins (B1).";
                case 319: return "";
                case 320: return "";
                case 321: return "Find: South Zil Desert.";
                case 322: return "Find: North Zil Desert.";
                case 323: return "Find: Mt. Typhoon (Peak). Buy: Dight.";
                case 324: return "Find End of the World (2).";
                case 325: return "Buy: Field Base.";
                case 326: return "Find: Volcano Base, Gaia(1). Drop: Great Susano-o";
                case 327: return "Drop: Kung Fu Master.";
                case 328: return "Find: Luzet Mountains (East).";
                case 329: return "Drop: Vengeful Spirit";
                case 330: return "Find: Volcano Crater.";
                case 331: return "Buy: Gumbo.";
                case 332: return "Sult Ruins (B1).";
                case 333: return "Find: Pirate Island, Gaia (1).";
                case 334: return "Find: Gaia (1) & (4) & Core. Drop: Gargoyle.";
                case 335: return "Find: Parm, Leck Mines (2), Ghost Ship (Lower Deck) & (Mid Deck). Buy: Parm, Steamer. Misc: Justin's Inventory (x3), Sue's Inventory(x2), Given to you by a girl in Parm..";
                case 336: return "Find: West Misty Forest, East Misty Forest. Buy: Luc Village.";
                case 337: return "Buy: Gumbo Village.";
                case 338: return "Find: Petrified Forest. Buy: Cafu Village. Misc: Rapp's Inventory.";
                case 339: return "Buy: Cafu Village Misc: Rapp's Inventory.";
                case 340: return "Find: Garlyle Base Barracks.";
                case 341: return "Find: Herb Mountains";
                case 342: return "Buy: New Parm.";
                case 343: return "Buy: New Parm.";
                case 344: return "Find: Steamer (Given to you by a sailor on the Steamer). Buy: New Parm.";
                case 345: return "";
                case 346: return "Find: Marna Road, Leck Mines (1), Ghost Ship, Dom Ruins (Vestibule), Herb Mountains. Buy: Parm, Steamer. Drop: Green Slime.";
                case 347: return "Find: Herb Mountains.";
                case 348: return "Find: East Misty Forest (2). Buy: New Parm, Luc Village.";
                case 349: return "Find: East Misty Forest, Valley of the Flying Dragon. Buy: Dight Village. Drop: Ent.";
                case 350: return "Find: Valley of the Flying Dragon (1). Buy: Dight Village.";
                case 351: return "Buy: Dight Village. Misc: Gadwin's Inventory.";
                case 352: return "Find: Mt. Typhoon. Buy: Dight Village.";
                case 353: return "Find: Mt. Typhoon. Buy: Dight Village.";
                case 354: return "Can be Location at 367 too : Find: Parm, Herb Mountains, Valley of the Flying Dragon (1). Buy: New Parm, Dight Village, Cafu Village. Drop: Spitting Cobra, Roadcrawler, Plop Mold, Land Slug.";
                case 355: return "Find: East Rangle Mountains, Misty Forest (3). Misc: Feena's Inventory.";
                case 356: return "Misc: Sue's Inventory.";
                case 357: return "Buy: Luc Village";
                case 358: return "Misc: Sue's Inventory.";
                case 359: return "Find: Parm, Dight Village. Buy: Steamer. Misc: Feena's Inventory";
                case 360: return "Misc: Rapp's Inventory";
                case 361: return "Find: Dom Ruins (Vestibule), Dom Ruins (Cliff). Drop: Skeleton.";
                case 362: return "Find: North Lama Mountains.";
                case 363: return "Find: Military Train, East Misty Forest (1), Underground Ruins (B2), Icarian City (3), Gaia. Buy: Zil Padon, Zil Padon Ruins. Drop: Hydra";
                case 364: return "Find: Volcano (1), Savanna Wilderness, Tower of Temptation (Entrance), East Luzet Mountains, Underground Railway Ruins (3), Icarian City (4), Gaia (2). Drop: Hydra, Phantom Dragon, Satan, Gaia Drago.";
                case 365: return "Find: Virgin Forest (4), Tower of Temptation (8th Floor), Icarian City (2), Gaia. Buy: Zil Padon, Zil Padon Ruins. Drop: Phantom Dragon, Slug Fish.";
                case 366: return "Buy: Zil Padon, Zil Padon Ruins.";
                case 367: return "Can be Location at 354 too: Find: Parm, Herb Mountains, Valley of the Flying Dragon (1). Buy: New Parm, Dight Village, Cafu Village. Drop: Spitting Cobra, Roadcrawler, Plop Mold, Land Slug.";
                case 368: return "Find: Valley of the Flying Dragon (2), Tower of Doom (1st Floor) & (3rd Floor). Buy: Dight Village, Gumbo Village. Drop: Mold Bird, Klepp Soldier, Toad King. Misc: Gadwin's Inventory (x2), Rapp's Inventory.";
                case 369: return "Buy: Field Base.";
                case 370: return "Find: Herb Mountains. Buy: Luc Village, Field Base.";
                case 371: return "Buy: Luc Village, Field Base. Misc: Feena's Inventory.";
                case 372: return "Find: Twin Towers (East). Buy: Luc Village. Drop: Tarantula, Giant Moth.";
                case 373: return "Find: God of Light Mountain, Twin Towers (West). Buy: Luc Village. Drop: Pit Viper, Sea Star.";
                case 374: return "Find: Sult Ruins (B2), Ghost Ship Hall, Dom Ruins (x2), Garlyle Base, God of Light Mountain (Peak), East Misty Forest (1), Valley of the Flying Dragon (2), Virgin Forest (2), North Zil Desert, Underground Ruins (1), Tower of Temptation (9th Floor). Buy: Luc Village, Dight Village. Drop: Gaia Bird, Crimsona, Hydra, Lilith. Misc: Guido's Inventory (x2).";
                case 375: return "Buy: Dight Village, Gumbo Village, Laine, Zil Padon Ruins. Drop: Toad King, Bird Skull.";
                case 376: return "Find: God of Light Mountain (Peak), End of the World (5), Twin Towers (South), Tower of Doom, Rainbow Mountain (Peak). Drop: Odd Bird.";
                case 377: return "Find: Dom Ruins (1), Valley of the Flying Dragon (3), Twin Towers (West), North Brinan Plateau, Abandoned Laine Village (Warp Space (2), Underground Ruins (2) & (4).";
                case 378: return "Find: Leck Mines (2), Volcano (1), Pirate Island, Petrified Forest (x2), South Zil Desert, Rainbow Mountain (Base). Drop: Dragon Knight, Jackal.";
                case 379: return "Find: East Misty Forest (3), End of the World (2), Twin Towers, Underground Ruins (4).";
                case 380: return "Find: Virgin Forest (2), Tower of Doom (Military Facility) & (2nd Floor), Underground Ruins (Shrine 1) & (4), West Luzet Mountains (x2), Field Base (1).";
                case 381: return "Find: Soldier's Graveyard (B5), Savanna Wilderness, Underground Ruins (4).";
                case 382: return "Find: Herb Mountains, God of Light Mountain, Mysterious Vanishing Hill, Petrified Forest, Brinan Plateau, Rainbow Mountain (Base), Field Base (1), Spirit Sanctuary.";
                case 383: return "Find: Mt. Typhoon (Peak), Virgin Forest (3), Petrified Forest, Underground Ruins (1). Drop: Brain Bat, Layelah, Toad Demon.";
                case 384: return "Find: Rangle Mountains (West), Savanna Wilderness, East Luzet Mountains. Drop: Ghost.";
                case 385: return "Original Location";
                case 386: return "Original Location";
                case 387: return "Original Location";
                case 388: return "Original Location";
                case 389: return "Original Location";
                case 390: return "Original Location";
                case 391: return "Original Location";
                case 392: return "Original Location";
                case 393: return "Buy: New Parm.";
                case 394: return "Buy: Luc Village.";
                case 395: return "Find: Merrill Road, New Parm, West Rangle Mountains, East Rangle Mountains, Dom Ruins (Cliff), Valley of the Flying Dragon (3) & (4), Mt. Typhoon, Typhoon Tower (1), Volcano (1), Petrified Forest, Castle of Dreams (Dining Hall), Savanna Wilderness (x2), Abandoned Laine Village (Warp Space (2), Underground Ruins (3), Alent. Drop: Squid King.";
                case 396: return "Buy: Gumbo Village.";
                case 397: return "Find: Leck Mines (1) & (2). Buy: Field Base.";
                case 398: return "Find: Sult Ruins (B2), Dom Ruins (Vestibule). Buy: Dight Village, Gumbo Village.";
                case 399: return "";
                case 400: return "Buy: Laine, Zil Padon Ruins. Drop: Manta Ray.";
                case 401: return "Buy: Zil Padon Ruins.";
                case 402: return "Buy: Cafu Village.";
                case 403: return "Find: Twin Towers (North). Buy: Zil Padon Ruins.";
                case 404: return "Buy: Cafu Village, Zil Padon Ruins.";
                case 405: return "Buy: Luc Village, Cafu Village.";
                case 406: return "Buy: Gumbo Village, Field Base.";
                case 407: return "Buy: Gumbo Village, Cafu Village, Zil Padon Ruins.";
                case 408: return "";
                case 409: return "Find: North Brinan Plateau. Buy: Laine.";
                case 410: return "Find: Soldier's Graveyard (1). Buy: Laine.";
                case 411: return "";
                case 412: return "Find: Volcano Slope (2). Buy: Luc.";
                case 413: return "";
                case 414: return "Buy: Field Base.";
                case 415: return "Find: Mt. Typhoon (Peak). Buy: New Parm.";
                case 416: return "";
                case 417: return "Find: End of the World (2), North Lama Mountains, Teleportation Room (1st Floor)).";
                case 418: return "";
                case 419: return "Find: West Misty Forest.";
                case 420: return "";
                case 421: return "Find: Valley of the Flying Dragon (4), Virgin Forest (1), East Savanna Wilderness.";
                case 422: return "Buy: Zil Padon.";
                case 423: return "Buy: Zil Padon.";
                case 424: return "";
                case 425: return "";
                case 426: return "Find: Tower of Temptation (5th Floor). Buy: Teleportation Room (Tower of Temptation).";
                case 427: return "";
                case 428: return "";
                case 429: return "Find: Dom Ruins, Garlyle Base, Underground Ruins (2). Drop: Elite Officer, Fire Hound.";
                case 430: return "Item Key";
                case 431: return "Item Key";
                case 432: return "Item Key";
                case 433: return "Item Key";
                case 434: return "Drop: Gaia Scorpion.";
                case 435: return "Drop: Lich.";
                case 436: return "Drop: Gaia Snake, Gaia Ape, Ruin Guard.";
                case 437: return "?";
                case 438: return "Not Used";
                case 439: return "Find: Mt. Typhoon (Peak), South Lama Mountains, Volcano, Twin Towers North, Mysterious Vanishing Hill, Virgin Forest(2).Drop: Plop Mold, Red Devil, Slipple, Rock Man.";
                case 440: return "Find: Merill Road.Buy : New Parm.";
                case 441: return "Buy: Laine, Zil Padon Ruins.";
                case 442: return "Find: Soldier's Graveyard (B3).";
                case 443: return "";
                case 444: return "Find: Abandoned Laine Village (Warp Space (1). Buy: Laine. Misc: Milda's Inventory";
                case 445: return "Find: Abandoned Laine Village (Warp Space (2) & (Warp Space (3). Buy: Laine. Misc: Milda's Inventory";
                case 446: return "Find: Tower of Doom (Army Facility). Buy: Field Base. Drop: Combatant";
                case 447: return "Buy: Zil Padon Ruins. Misc: Liete's Inventory.";
                case 448: return "Not Used";
                case 449: return "Find: Virgin Forest (1). Buy: Zil Padon Ruins.";
                case 450: return "Find: West Luzet Mountains. Buy: Zil Padon Ruins. Misc: Liete's Inventory.";
                case 451: return "Buy: Field Base.";
                case 452: return "Find: East Rangle Mountains, Gaia (2). Drop: Jackal, Dragon Knight.";
                case 453: return "Find: Abandoned Laine Village (Warp Space (3), Rainbow Mountain (Peak), Roof of Tower of Temptation.";
                case 454: return "Drop: Naga Queen.";
                case 455: return "Find: End of the World (2), Underground Railway Ruins (1).";
                case 456: return "Find: Soldier's Graveyard (B4 East), Spirit Sanctuary (1).";
                case 457: return "Find: Pirate Island, Rainbow Mountain (Base).";
                case 458: return "Find: Valley of the Flying Dragon (2), Underground Ruins (B1), Spirit Sanctuary (1).";
                case 459: return "Find: Grandeur (Passageway), Spirit Sanctuary.";
                case 460: return "Original Location";
                case 461: return "Original Location";
                case 462: return "Original Location";
                case 463: return "Find: Roof of Tower of Temptation.";
                case 464: return "Liete's Initial Equipment";
                case 465: return "Drop: Slug Fish";
                case 466: return "Buy: Gumbo Village.";
                case 467: return "Buy: Zil Padon Ruins.";
                case 468: return "Find: Soldier's Graveyard (B4 East).";
                case 469: return "";
                case 470: return "Not Used";
                case 471: return "Find: Top of Tower of Temptation.";
                case 472: return "Find; Tower of Temptation's Roof.";
                case 473: return "Teleportation Room (Tower Of Temptation)";
                case 474: return "Teleportation Room (Tower Of Temptation)";
                case 475: return "Original Location";
                case 476: return "Original Location";
                case 477: return "Original Location";
                case 478: return "Original Location";
                case 479: return "";
                case 480: return "Item Key";
                case 481: return "Not Available";
                case 482: return "Not Available";
                case 483: return "Not Available";
                case 484: return "Not Available";
                case 485: return "Not Available";
                case 486: return "Not Available";
                case 487: return "Not Available";
                case 488: return "Not Available";
                case 489: return "Original Location";
                case 490: return "Original Location";
                case 491: return "Original Location";
                case 492: return "Original Location";
                case 493: return "Original Location";
                case 494: return "Original Location";
                case 495: return "Original Location";
                case 496: return "Original Location";
                case 497: return "Original Location";
                case 498: return "Original Location";
                case 499: return "Original Location";
                case 500: return "Original Location";
                case 501: return "Original Location";
                case 502: return "Original Location";
                case 503: return "Original Location";
                case 504: return "Original Location";
                case 505: return "Original Location";
                case 506: return "Original Location";
                case 507: return "Original Location";
                case 508: return "Original Location";
                case 509: return "";
                case 510: return "";
                case 511: return "";
                default: return "";
            }
        }

    }
}
